# Generated by Django 5.1.6 on 2025-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogVideos/'),
        ),
    ]
